### ISSUE TITLE
Test contains negative tests where URNs are expected to fail in place of URLs

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/vc-data-model-2-test-suite#5]
https://github.com/w3c/vc-data-model/issues/1160

Basically URNs are URLs now meaning that some test data found in this suite might be invalid such as:

https://github.com/digitalbazaar/vc-data-model-2-test-suite/blob/main/tests/input/credential-issuer-nonurl-fail.json

https://github.com/digitalbazaar/vc-data-model-2-test-suite/blob/6884551bb388784032d40a222340995c55adc75e/example-server.js#L95-L98

**Comment by clehner** [comment]
My mistake (also: https://github.com/1EdTech/openbadges-specification/issues/533#issuecomment-1643400172)
I think you have fixed it in #7

**Comment by aljones15** [comment]
closing as this has been addressed
